services:
  vulnerable-web:
    image: nginx:alpine
    container_name: vulnerable-nginx
    depends_on:
      - insecure-db
      - app
    ports:
      - "127.0.0.1:8080:80"
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /tmp
    cap_drop:
      - ALL
    user: "nginx"

  insecure-db:
    image: postgres:16-alpine
    container_name: insecure-db
    environment:
      - POSTGRES_DB=vulnapp
      - POSTGRES_USER=vulnuser
      # лучше вынести в .env или secret-file; для лабы можно хотя бы через .env
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U vulnuser -d vulnapp"]
      interval: 10s
      timeout: 3s
      retries: 5

  app:
    image: python:3.11-alpine
    container_name: vulnerable-app
    depends_on:
      - insecure-db
    working_dir: /app
    volumes:
      - ./app:/app:rw
    command: ["python", "app.py"]
    environment:
      - DB_URL=postgresql://vulnuser:${POSTGRES_PASSWORD}@insecure-db:5432/vulnapp
      - DEBUG=false
      - APP_SECRET_KEY=${APP_SECRET_KEY}
    ports:
      - "127.0.0.1:5001:5000"
    security_opt:
      - no-new-privileges:true
