---
site_name: AppSecCource
site_url: "https://geminishkv.github.io/course_labs/"

theme:
  name: material
  language: ru
  logo: artifacts/assets/logo.png
  favicon: artifacts/assets/favicon.ico
  font:
    text: Montserrat
    code: Roboto Mono
  features:
    - search.highlight
    - content.code.copy
    - navigation.tabs.sticky
    - navigation.top
    - search.share
    - search.suggest
    - content.code.copy
    - analytics
    - content.tables

plugins:
  - search
  - macros
  - mkdocs-pdf

markdown_extensions:
  - def_list
  - md_in_html
  - attr_list

nav:
  - "Главная страница": index.md
  - "Лабораторные работы":
      - "Лабораторная работа №1": labs/lab01.md
      - "Лабораторная работа №2": labs/lab02.md
      - "Лабораторная работа №3": labs/lab03.md
      - "Лабораторная работа №4": labs/lab04.md
      - "Лабораторная работа №5": labs/lab05.md
  - "Приложение": APPENDIX.md
  - "Материалы":
      - "Лекции": course.md
      - "Примеры":
          - "Аналитические кейсы": exmpl.md
          - "Использование MultiSiq": Multisignature.md
          - "PrintNightmare Vulnerability": PrintNightmare.md
          - "Risk Analysis": RA.md
      - "Лицензии ПО": licenses.md
      - "Классификация инструментов": appsec_tt.md
      - "OWASP TOP 10":
          - "CI/CD Risks": OWASP_Top_10_CICD_Risks.md
          - "Authorization": Authorization.md
          - "Authentication": Authentication.md
          - "Client-side Attacks": Client-side Attacks.md
          - "Command Execution": Command Execution.md
          - "Logical Attacks": Logical Attacks.md
          - "Information Disclosure": Information Disclosure.md
  - "CheatSheet":
      - "Docker": artifacts/cheatsheet/CHEATSHEET_DOCKER.md
      - ".dockerignore": artifacts/cheatsheet/CHEATSHEET_DOCKERIGNORE.md
      - "GitHub CLI": artifacts/cheatsheet/CHEATSHEET_GH_CLI.md
      - "GitSCM": artifacts/cheatsheet/CHEATSHEET_GIT.md
      - ".gitignore": artifacts/cheatsheet/CHEATSHEET_GITIGNORE.md
  - "Contributor Covenant": Contributor Covenant.md
  - "Политика безопасности": Security.md
  - "Карта сертификации ГОСТ 56939-2024":
      >-
        https://storage.yandexcloud.net/aft-tilda/%D0%A2%D0%B8%D0%BF%D0%BE%D0%B2%D0%BE%D0%B9%20%D0%BF%D1%80%D0%BE%D1%86%D0%B5%D1%81%D1%81%20%D0%B1%D0%B5%D0%B7%D0%BE%D0%BF%D0%B0%D1%81%D0%BD%D0%BE%D0%B9%20%D1%80%D0%B0%D0%B7%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D0%BA%D0%B8%20%D0%B4%D0%BB%D1%8F%20%D1%84%D0%B8%D0%BD%D1%82%D0%B5%D1%85%D0%B0.pdf
  - "AppSec Toolchain Map": "https://geminishkv.github.io/oss_toolchainmap/research-notes/"
  - "FinDevSecOps": "https://findevsecops.ru/"
  - "АО ЛАНИТ": "https://www.lanit.ru"
  - "О проекте": about.md

extra_css:
  - stylesheets/header.css
  - stylesheets/footer.css
  - stylesheets/search.css
  - stylesheets/sidebar.css
  - stylesheets/typeset.css
  - stylesheets/tools-overlay.css
  - stylesheets/burger.css
  - stylesheets/mobile-logo.css

extra_javascript:
  - javascripts/custom-title.js

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/geminishkv
    - icon: fontawesome/solid/code-branch
      link: https://github.com/geminishkv/course_labs
    - icon: fontawesome/brands/telegram
      link: https://t.me/shmakovis_appsec
    - icon: fontawesome/regular/envelope
      link: mailto:shmakovis@inbox.ru
