---
site_name: AppSecCource
site_url: "https://geminishkv.github.io/course_labs/"

theme:
  name: material
  language: ru
  logo: artifacts/assets/logo.png
  favicon: artifacts/assets/favicon.ico
  font:
    text: Montserrat
    code: Roboto Mono
  features:
    - navigation.indexes
    - search.highlight
    - content.code.copy
    - navigation.tabs.sticky
    - navigation.top
    - search.share
    - search.suggest
    - content.code.copy
    - analytics
    - content.tables

plugins:
  - search
  - macros
  - mkdocs-pdf
  - include-markdown:
      heading_offset: 0
      preserve_includer_indent: false
      dedent: true

markdown_extensions:
  - def_list
  - md_in_html
  - attr_list
  - admonition
  - toc:
      permalink: false
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.snippets:
      check_paths: true

watch:
  - docs

extra_css:
  - stylesheets/header.css
  - stylesheets/footer.css
  - stylesheets/search.css
  - stylesheets/sidebar.css
  - stylesheets/typeset.css
  - stylesheets/tools-overlay.css
  - stylesheets/burger.css
  - stylesheets/mobile-logo.css
  - stylesheets/layout.css

extra_javascript:
  - javascripts/custom-title.js
  - javascripts/typewriter-target.js

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/geminishkv
    - icon: fontawesome/solid/code-branch
      link: https://github.com/geminishkv/course_labs
    - icon: fontawesome/brands/telegram
      link: https://t.me/shmakovis_appsec
    - icon: fontawesome/regular/envelope
      link: mailto:shmakovis@inbox.ru

nav:
  - "Главная страница": index.md
  - "Лабораторные работы":
      - "Лабораторная работа №1": labs/lab01.md
      - "Лабораторная работа №2": labs/lab02.md
      - "Лабораторная работа №3": labs/lab03.md
      - "Лабораторная работа №4": labs/lab04.md
      - "Лабораторная работа №5": labs/lab05.md
      - "Лабораторная работа №6": labs/lab06.md
      - "Лабораторная работа №7": labs/lab07.md
      - "Лабораторная работа №8": labs/lab08.md
      - "Лабораторная работа №9": labs/lab09.md
      - "Лабораторная работа №10": labs/lab10.md
      - "pet_project": labs/pet_project.md
  - "Материалы":
      - "Лекции": course.md
      - "Примеры":
          - "Аналитические кейсы": exmpl.md
          - "Использование MultiSiq": Multisignature.md
          - "PrintNightmare": PrintNightmare.md
          - "Risk Analysis": RA.md
      - "Лицензии ПО": licenses.md
      - "Классификация инструментов": appsec_tt.md
      - "OWASP TOP 10":
          - "CI/CD Risks": OWASP_Top_10_CICD_Risks.md
          - "Authorization": Authorization.md
          - "Authentication": Authentication.md
          - "Client-side Attacks": Client-side Attacks.md
          - "Command Execution": Command Execution.md
          - "Logical Attacks": Logical Attacks.md
          - "Information Disclosure": Information Disclosure.md
  - "CheatSheet":
      - "Docker": artifacts/cheatsheet/CHEATSHEET_DOCKER.md
      - ".dockerignore": artifacts/cheatsheet/CHEATSHEET_DOCKERIGNORE.md
      - "GitHub CLI": artifacts/cheatsheet/CHEATSHEET_GH_CLI.md
      - "GitSCM": artifacts/cheatsheet/CHEATSHEET_GIT.md
      - ".gitignore": artifacts/cheatsheet/CHEATSHEET_GITIGNORE.md
  - "Приложение": APPENDIX.md
  - "AppSec Toolchain Map": "https://geminishkv.github.io/oss_toolchainmap/research-notes/"
  - "FinDevSecOps": "https://findevsecops.ru/"
  - "АО ЛАНИТ": "https://www.lanit.ru"
  - "Блог": channel.md
  - "О проекте": about.md
  - "Релизы": RELEASE_NOTES.md
  - "Политика безопасности": Security.md
