---
site_name: AppSecCource
site_url: "https://geminishkv.github.io/course_labs/"
site_description: >
  Практический курс по прикладной безопасности приложений: лабораторные работы и аннотационные материалы 
  для прокачки навыков в ИБ (информационной безопасности), а также чеклисты и методички по AppSec, DevSecOps 
  и OWASP Top 10.
site_author: "Илья Шмаков"

theme:
  name: material
  language: ru
  logo: artifacts/assets/logo.png
  icon:
    menu: fontawesome/solid/bars-staggered
    top: fontawesome/solid/angles-up
    down: fontawesome/solid/angles-down
    previous: fontawesome/solid/angles-left
    next: fontawesome/solid/angles-right
    close: fontawesome/solid/xmark
  favicon: artifacts/assets/favicon.ico
  font:
    text: Montserrat
    code: Segoe UI
  features:
    - navigation.indexes
    - search.highlight
    - navigation.tabs.sticky
    - navigation.top
    - search.share
    - search.suggest
    - analytics
    - content.tables
    - content.code.copy
    - content.code.select
    - content.code.annotate
    - content.action.view
    - navigation.instant
    - navigation.instant.prefetch
    - content.lazy

plugins:
  - search
  - macros
  - mkdocs-pdf
  - include-markdown:
      heading_offset: 0
      preserve_includer_indent: false
      dedent: true

markdown_extensions:
  - def_list
  - md_in_html
  - attr_list
  - fenced_code
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
      use_pygments: true
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - toc:
      permalink: false
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.tabbed
  - pymdownx.details
  - pymdownx.tasklist
  - pymdownx.magiclink
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.smartsymbols

watch:
  - docs

extra_css:
  - stylesheets/header.css
  - stylesheets/footer.css
  - stylesheets/search.css
  - stylesheets/sidebar.css
  - stylesheets/typeset.css
  - stylesheets/tools-overlay.css
  - stylesheets/burger.css
  - stylesheets/mobile-logo.css
  - stylesheets/layout.css
  - stylesheets/clipboard.css

extra_javascript:
  - javascripts/custom-title.js
  - javascripts/typewriter-target.js

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/geminishkv
    - icon: fontawesome/solid/code-branch
      link: https://github.com/geminishkv/course_labs
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/u/geminishkvdev
    - icon: fontawesome/brands/telegram
      link: https://t.me/shmakovis_appsec
    - icon: fontawesome/brands/instagram
      link: https://instagram.com/geminishkv
    - icon: fontawesome/brands/Linkedin-in
      link: https://www.linkedin.com/in/geminishkvdev
    - icon: fontawesome/regular/envelope-open
      link: mailto:shmakovis@inbox.ru
    - icon: fontawesome/solid/rss
      link: https://geminishkv.github.io/course_labs/feed.xml

nav:
  - "Главная страница": index.md
  - "Лабораторные работы":
      - "Лабораторная работа №1": labs/lab01.md
      - "Лабораторная работа №2": labs/lab02.md
      - "Лабораторная работа №3": labs/lab03.md
      - "Лабораторная работа №4": labs/lab04.md
      - "Лабораторная работа №5": labs/lab05.md
      - "Лабораторная работа №6": labs/lab06.md
      - "Лабораторная работа №7": labs/lab07.md
      - "Лабораторная работа №8": labs/lab08.md
      - "Лабораторная работа №9": labs/lab09.md
      - "Лабораторная работа №10": labs/lab10.md
      - "pet_project": labs/pet_project.md
  - "Материалы":
      - "Примеры":
          - "Аналитические кейсы": materials/examples/exmpl.md
          - "Использование MultiSiq": materials/examples/Multisignature.md
          - "PrintNightmare": materials/examples/PrintNightmare.md
          - "Risk Analysis": materials/examples/RA.md
      - "Лицензии ПО": licenses.md
      - "Классификация инструментов": appsec_tt.md
      - "OWASP TOP 10":
          - "CI/CD Risks": materials/OWASPTOP10/OWASP_Top_10_CICD_Risks.md
          - "Authorization": materials/OWASPTOP10/Authorization.md
          - "Authentication": materials/OWASPTOP10/Authentication.md
          - "Client-side Attacks": materials/OWASPTOP10/Client-side Attacks.md
          - "Command Execution": materials/OWASPTOP10/Command Execution.md
          - "Logical Attacks": materials/OWASPTOP10/Logical Attacks.md
          - "Information Disclosure": materials/OWASPTOP10/Information Disclosure.md
  - "CheatSheet":
      - "GitHub CLI": artifacts/cheatsheet/CHEATSHEET_GH_CLI.md
      - "GitSCM": artifacts/cheatsheet/CHEATSHEET_GIT.md
      - "Docker": artifacts/cheatsheet/CHEATSHEET_DOCKER.md
      - ".dockerignore": artifacts/cheatsheet/CHEATSHEET_DOCKERIGNORE.md
      - ".gitignore": artifacts/cheatsheet/CHEATSHEET_GITIGNORE.md
  - "Приложение": APPENDIX.md
  - "Блог": channel.md
  - "О проекте": about.md
  - "Релизы": RELEASE_NOTES.md
  - "Политика безопасности": Security.md
  - "AppSec Toolchain Map": "https://geminishkv.github.io/oss_toolchainmap/research-notes/"
  - "FinDevSecOps": "https://findevsecops.ru/"
  - "АО ЛАНИТ": "https://www.lanit.ru"